export enum DoctorType {
    FAMILY_MEDICINE = "FAMILY_MEDICINE",
    DERMATOLOGIST = "DERMATOLOGIST",
    HEMATOLOGIST = "HEMATOLOGIST",
    CARDIOLOGIST = "CARDIOLOGIST",
    NEUROLOGIST = "NEUROLOGIST"
  }
  